// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#include "cerberus_utility_status_codes.h"


#define STATUS_RESERVED_STR "Reserved"

/**
 * Strings for the utility completion statuses.
 */
const char *cerberus_utility_errors_str[] = {
	[STATUS_SUCCESS] = "Command completed successfully.",
	[STATUS_CRC_FAILURE] = "Incoming packet had invalid CRC.",
	[STATUS_INVALID_PACKET] = "Incoming packet had invalid data.",
	[STATUS_INVALID_MANIFEST] = "No valid manifest found.",
	[STATUS_COMMUNICATION_FAILURE] = "Failure while communicating with Cerberus: %s",
	[STATUS_UPDATE_FAILURE] = "Failure while performing update.",
	[STATUS_NO_MEM] = "Failed to allocate memory for operation.",
	[STATUS_INVALID_UPDATE_FILE] = "Provided file (%s) cannot be found.",
	[STATUS_UNKNOWN_REQUEST] = "User request unknown.",
	[STATUS_INVALID_INPUT] = "Invalid input.",
	[STATUS_PAYLOAD_TOO_LARGE] = "Payload too large for MCTP.",
	[STATUS_MCTP_TIMEOUT] = "Timeout while waiting for MCTP response.",
	[STATUS_PARTIAL_PACKET] = "Partial MCTP packet received.",
	[STATUS_NO_DATA] = "No data received.",
	[STATUS_UNKNOWN] = "Unknown failure.",
	[STATUS_UNEXPECTED_RLEN] = "Unexpected response length: Expected %zu but got %zu.",
	[STATUS_CMD_RESPONSE] = "Unexpected command response: Expected %d but got %d.",
	[STATUS_EMPTY_FILE] = "Provided file (%s) empty.*/",
	[STATUS_READ_FILE_FAILED] = "Failed to read provided file (%s).",
	[STATUS_OPEN_FILE_FAILED] = "Failed to open provided file (%s).",
	[STATUS_OPERATION_TIMEOUT] = "Timeout while performing an operation.",
	[STATUS_STRING_NOT_TERMINATED] = "String value is not null terminated.",
	[STATUS_BUF_TOO_SMALL] = "Value is larger than container.",
	[STATUS_NOT_STRING] = "Value is not a printable string: %x",
	[STATUS_ATTESTATION_FAILURE] = "Device failed attestation.",
	[STATUS_MCTP_FAILURE] = "MCTP layer error received: %s",
	[STATUS_RESERVED_26] = STATUS_RESERVED_STR,
	[STATUS_RESERVED_27] = STATUS_RESERVED_STR,
	[STATUS_RESERVED_28] = STATUS_RESERVED_STR,
	[STATUS_FW_NOT_SUPPORTED_BY_MANIFEST] = "FW version provided not provided by active manifest.",
	[STATUS_CERBERUS_CMD_UNSUPPORTED] = "Command sent not supported by Cerberus.",
	[STATUS_UNSUPPORTED_FORMAT] = "Log stored in an unsupported format: 0x%02X",
	[STATUS_RESERVED_34] = STATUS_RESERVED_STR,
	[STATUS_COMPLETE_PACKET] = "Complete packet received.",
	[STATUS_RESERVED_36] = STATUS_RESERVED_STR,
	[STATUS_OUTPUT_FILE_REQUIRED] = "Output file needed for response data.",
	[STATUS_WRITE_FILE_FAILED] = "Failed to write to provided file (%s).",
	[STATUS_CERBERUS_CMD_NOT_AUTHORIZED] = "Command is not authorized for execution.",
	[STATUS_RESERVED_40] = STATUS_RESERVED_STR,
	[STATUS_UNEXPECTED_VALUE] = "Unexpected value: Expected %d but got %d.",
	[STATUS_INVALID_RECOVERY_IMAGE] = "No valid recovery image found for port %i.",
	[STATUS_INVALID_PORT] = "Invalid communication port specified.",
	[STATUS_RESERVED_44] = STATUS_RESERVED_STR,
	[STATUS_RESERVED_45] = STATUS_RESERVED_STR,
	[STATUS_RESERVED_46] = STATUS_RESERVED_STR,
	[STATUS_RESERVED_47] = STATUS_RESERVED_STR,
	[STATUS_RESERVED_48] = STATUS_RESERVED_STR,
	[STATUS_RESERVED_49] = STATUS_RESERVED_STR,
	[STATUS_PROTOCOL_INCOMPATIBLE] = "Protocol v%i is not compatible with the request.",
	[STATUS_BAD_MCTP_PARAMETERS] = "MCTP parameters are not valid.",
	[STATUS_NO_CERTIFICATE] = "No certificate available.",
	[STATUS_NO_DEVICE] = "No device is available.",
	[STATUS_MSFT_VID_SET_UNSUPPORTED] = "Device does not support Microsoft VID command set.",
	[STATUS_NO_KEY] = "Key not selected before crypto operation.",
	[STATUS_INVALID_KEY] = "Key invalid for requested crypto operation.",
	[STATUS_SIG_VERIFY_FAIL] = "Signature verification failed.",
	[STATUS_UNSUPPORTED_OPERATION] = "Requested operation unsupported.",
	[STATUS_KEY_LENGTH_UNSUPPORTED] = "Key length is not supported.",
	[STATUS_ENCRYPTION_OUT_OF_SESSION]= "Encrypted packet received out of session.",
	[STATUS_CERT_NOT_SELF_SIGNED] = "Certificate not self signed.",
	[STATUS_CERT_SELF_SIGNED] = "Certificate self signed.",
	[STATUS_CERT_NOT_CA] = "Certificate not for a CA.",
	[STATUS_CERT_INVALID_SIGNATURE] = "Invalid signature.",
	[STATUS_CERT_INVALID_CERT] = "Invalid certificate.",
	[STATUS_CERT_SIG_TYPE_UNSUPPORTED] = "Unsupported signature type.",
	[STATUS_OPERATION_UNSUPPORTED_BY_DEVICE] = "Requested command not supported by device.",
	[STATUS_SESSION_ESTABLISHMENT_FAILED] = "Failed to establish a secure session.",
	[STATUS_LOG_CONTENTS_INCONSISTENT] = "Log contains inconsistent information.",
	[STATUS_LOG_LEN_INVALID] = "Log not large enough for contents.",
	[STATUS_MUTEX_FAILURE] = "Failure during a mutex operation: %s (errno %d)",
	[STATUS_CRYPTO_FAILURE] = "Failure during a crypto library operation.",
	[STATUS_MCTP_READ_FAILURE] = "Failure during MCTP read.",
	[STATUS_CERT_PROVISIONING_LOCKED] = "Certificate provisioning locked.",
	[STATUS_RESERVED_75] = STATUS_RESERVED_STR,
	[STATUS_I2C_ENABLE_SLAVE_MODE_FAILURE] = "Failed to enable I2C slave mode.",
	[STATUS_MUTEX_SHM_OPEN_FAILURE] = "Failed to open share memory for mutex: %s (errno %d)",
	[STATUS_MUTEX_MAP_SHM_FAILURE] = "Failed to map share memory for mutex: %s (errno %d)",
	[STATUS_MUTEX_TRUNCATE_SHM_FAILURE] = "Failed to truncate share memory for mutex: %s (errno %d)",
	[STATUS_MUTEX_INIT_ATTR_FAILURE] = "Failed to initialize mutex attributes: %s (errno %d)",
	[STATUS_MUTEX_SET_SHARED_ATTR_FAILURE] = "Failed to set mutex process-shared attribute: %s (errno %d)",
	[STATUS_MUTEX_SET_ATTR_TYPE_FAILURE] = "Failed to set attribute type for mutex: %s (errno %d)",
	[STATUS_MUTEX_SET_ROBUS_ATTR_FAILURE] = "Failed to set robustness attribute for mutex: %s (errno %d)",
	[STATUS_MUTEX_INIT_FAILURE] = "Failed to initialize mutex: %s (errno %d)",
	[STATUS_MUTEX_ALLOCATE_MEMORY_FAILURE] = "Failed to allocate memory for mutex: %s (errno %d)",
	[STATUS_MUTEX_CREATE_FAILURE] = "Failed to create mutex: %s (errno %d)",
	[STATUS_MUTEX_WAIT_TIMEOUT_FAILURE] = "Wait mutex timeout: %s (errno %d)",
	[STATUS_REBOOT_AFTER_UPDATE_FAILURE] = "Failed to reboot after %s update",
	[STATUS_MCTP_WRITE_FAILURE] = "Failure during MCTP write.",
	[STATUS_MCTP_CTRL_REQ_FAIL] = "MCTP control request failed with completion code %x",
	[STATUS_MBEDTLS_FAILURE] = "Failed to execute mbedtls operation %x",
	[STATUS_BOUNDARY_REACHED] = "Boundary reached and can't Increment/Decrement",
	[STATUS_RESERVED_94] = STATUS_RESERVED_STR,
	[STATUS_UNSUPPORTED_DIGEST_LEN] = "Unsupported digest length %d",
};
